# Generated by Django 4.2.30 on 2026-07-09 22:01

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail institucional')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='deve trocar a senha no próximo login')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('papel', models.CharField(choices=[('SOLICITANTE', 'Solicitante'), ('SECRETARIO', 'Secretário da Pasta'), ('AUTORIZADOR', 'Autorizador Final'), ('TESOURARIA', 'Tesouraria'), ('CONTROLE_INTERNO', 'Controle Interno/Auditoria'), ('ADMIN', 'Administrador do Sistema')], max_length=20)),
                ('nivel_fiducia', models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIARIO', 'Intermediário'), ('ELEVADO', 'Elevado')], default='BASICO', max_length=20)),
                ('limite_autorizacao', models.DecimalField(blank=True, decimal_places=2, help_text='RF07 — usado apenas para o papel Autorizador Final.', max_digits=14, null=True, verbose_name='limite de alçada (valor máximo autorizável)')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
            },
        ),
        migrations.CreateModel(
            name='TentativaAcessoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sucesso', models.BooleanField()),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Tentativa de Acesso',
                'verbose_name_plural': 'Tentativas de Acesso',
                'indexes': [models.Index(fields=['email', 'criado_em'], name='accounts_te_email_28947d_idx')],
            },
        ),
    ]
