# Generated by Django 4.2.30 on 2026-07-09 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Positivo para crédito, negativo para débito.', max_digits=14)),
                ('origem', models.CharField(choices=[('SALDO_INICIAL', 'Saldo Inicial'), ('PAGAMENTO', 'Baixa de Pagamento'), ('ESTORNO', 'Estorno de Pagamento'), ('CONCILIACAO', 'Baixa por Conciliação Bancária'), ('AJUSTE_MANUAL', 'Lançamento Manual (Contingência)')], max_length=20)),
                ('justificativa', models.CharField(blank=True, max_length=255)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cadastros.contabancaria')),
            ],
            options={
                'verbose_name': 'Movimentação de Conta',
                'verbose_name_plural': 'Movimentações de Conta',
                'ordering': ['-criado_em'],
            },
        ),
    ]
