# Generated by Django 4.2.30 on 2026-07-09 22:04

import apps.pagamentos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('protocolo', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('numero_ne', models.CharField(blank=True, max_length=40, verbose_name='Número da Nota de Empenho')),
                ('numero_nf', models.CharField(blank=True, max_length=40, verbose_name='Número da Nota Fiscal')),
                ('exceto_ne_nf', models.BooleanField(default=False, help_text='Exceção cadastrada pelo Administrador — RN do módulo M2.', verbose_name='Dispensado de NE/NF (despesa de pequeno vulto)')),
                ('vencimento', models.DateField()),
                ('competencia', models.CharField(help_text='Formato MM/AAAA', max_length=7)),
                ('criticidade', models.CharField(choices=[('URGENTE', 'Urgente'), ('ALTA', 'Alta'), ('MEDIA', 'Média'), ('BAIXA', 'Baixa')], default='MEDIA', max_length=10)),
                ('urgente', models.BooleanField(default=False)),
                ('justificativa_urgencia', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO_SECRETARIO', 'Aprovado pelo Secretário'), ('AUTORIZADO', 'Autorizado'), ('PAGO', 'Pago'), ('DEVOLVIDO', 'Devolvido'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=25)),
                ('enviado_para_aprovacao', models.BooleanField(default=False)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('TED', 'TED'), ('PIX', 'PIX'), ('BOLETO', 'Boleto'), ('CHEQUE', 'Cheque')], max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('comprovante_pagamento', models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/')),
                ('estornado', models.BooleanField(default=False)),
                ('justificativa_estorno', models.TextField(blank=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_vinculados', to='cadastros.contabancaria')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cadastros.contrato')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cadastros.fornecedor')),
                ('natureza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cadastros.naturezadespesa')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cadastros.orgaosecretaria')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Pagamento',
                'verbose_name_plural': 'Pedidos de Pagamento',
                'ordering': ['-criticidade', 'vencimento'],
            },
        ),
        migrations.CreateModel(
            name='OrdemPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('autorizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_emitidas', to=settings.AUTH_USER_MODEL)),
                ('pedidos', models.ManyToManyField(related_name='ordens_pagamento', to='pagamentos.pedidopagamento')),
            ],
            options={
                'verbose_name': 'Ordem de Pagamento',
                'verbose_name_plural': 'Ordens de Pagamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoStatusPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('APROVADO_SECRETARIO', 'Aprovado pelo Secretário'), ('AUTORIZADO', 'Autorizado'), ('PAGO', 'Pago'), ('DEVOLVIDO', 'Devolvido'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], max_length=25, null=True)),
                ('status_novo', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO_SECRETARIO', 'Aprovado pelo Secretário'), ('AUTORIZADO', 'Autorizado'), ('PAGO', 'Pago'), ('DEVOLVIDO', 'Devolvido'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], max_length=25)),
                ('justificativa', models.TextField(blank=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pagamentos.pedidopagamento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('NF', 'Nota Fiscal'), ('NE', 'Nota de Empenho'), ('COMPROVANTE', 'Comprovante'), ('ATESTO', 'Termo de Atesto de Recebimento'), ('OUTRO', 'Outro')], max_length=15)),
                ('arquivo', models.FileField(upload_to=apps.pagamentos.models.anexo_upload_path)),
                ('servidor_responsavel', models.CharField(blank=True, help_text='Obrigatório quando tipo = Termo de Atesto (RN do módulo M2).', max_length=150, verbose_name='Servidor responsável pelo atesto')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='pagamentos.pedidopagamento')),
            ],
            options={
                'verbose_name': 'Anexo do Pedido',
                'verbose_name_plural': 'Anexos do Pedido',
            },
        ),
        migrations.AddIndex(
            model_name='pedidopagamento',
            index=models.Index(fields=['status'], name='pagamentos__status_9972cc_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidopagamento',
            index=models.Index(fields=['vencimento'], name='pagamentos__vencime_55859d_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidopagamento',
            index=models.Index(fields=['orgao', 'status'], name='pagamentos__orgao_i_b956f1_idx'),
        ),
    ]
