# Generated by Django 4.2.30 on 2026-07-09 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEmpenhoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('exercicio', models.PositiveIntegerField()),
                ('valor_empenhado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('liquidado', models.BooleanField(default=False)),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_empenho', to='cadastros.orgaosecretaria')),
            ],
            options={
                'verbose_name': 'Nota de Empenho (referência externa)',
                'verbose_name_plural': 'Notas de Empenho (referência externa)',
            },
        ),
    ]
