# Generated by Django 4.2.30 on 2026-07-09 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('pagamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='extratos/%Y/%m/')),
                ('formato', models.CharField(choices=[('PDF', 'PDF (texto)'), ('CSV', 'CSV'), ('OPEN_FINANCE', 'Open Finance (API)')], max_length=15)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('status_processamento', models.CharField(choices=[('PENDENTE', 'Pendente de Processamento'), ('PROCESSADO', 'Processado'), ('ERRO', 'Erro no Processamento')], default='PENDENTE', max_length=15)),
                ('erro_mensagem', models.TextField(blank=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extratos', to='cadastros.contabancaria')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extrato Bancário',
                'verbose_name_plural': 'Extratos Bancários',
                'ordering': ['-periodo_fim'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data', models.DateField()),
                ('historico', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], max_length=10)),
                ('identificador_transacao', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Conciliação'), ('CONCILIADO_AUTOMATICO', 'Conciliado Automaticamente'), ('CONCILIADO_MANUAL', 'Conciliado Manualmente'), ('IGNORADO', 'Ignorado (não é pagamento a fornecedor)')], default='PENDENTE', max_length=25)),
                ('extrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='conciliacao.extratobancario')),
                ('pedido_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_conciliados', to='pagamentos.pedidopagamento')),
            ],
            options={
                'verbose_name': 'Lançamento de Extrato',
                'verbose_name_plural': 'Lançamentos de Extrato',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('AUTOMATICA', 'Automática'), ('MANUAL', 'Manual')], max_length=12)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='conciliacao.lancamentoextrato')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_conciliacao', to='pagamentos.pedidopagamento')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Conciliação',
                'verbose_name_plural': 'Logs de Conciliação',
                'ordering': ['-criado_em'],
            },
        ),
    ]
