# Generated by Django 4.2.30 on 2026-07-09 22:01

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteRecursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('grupos_despesa_permitidos', models.JSONField(default=list, help_text='Lista de códigos de GrupoDespesa compatíveis com esta fonte.')),
            ],
            options={
                'verbose_name': 'Fonte de Recursos',
                'verbose_name_plural': 'Fontes de Recursos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_pessoa', models.CharField(choices=[('FISICA', 'Pessoa Física'), ('JURIDICA', 'Pessoa Jurídica')], max_length=10)),
                ('cnpj_cpf', models.CharField(max_length=18, unique=True, verbose_name='CNPJ/CPF')),
                ('nome', models.CharField(max_length=200, verbose_name='Razão social / Nome')),
                ('situacao_cadastral', models.CharField(choices=[('REGULAR', 'Regular'), ('PENDENTE', 'Pendência Cadastral'), ('IRREGULAR', 'Irregular/Sancionado')], default='REGULAR', max_length=10)),
                ('motivo_pendencia', models.CharField(blank=True, max_length=255)),
                ('banco', apps.core.fields.EncryptedTextField(blank=True)),
                ('agencia', apps.core.fields.EncryptedTextField(blank=True)),
                ('conta', apps.core.fields.EncryptedTextField(blank=True)),
                ('chave_pix', apps.core.fields.EncryptedTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fornecedor/Credor',
                'verbose_name_plural': 'Fornecedores/Credores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='NaturezaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=150)),
                ('criticidade_padrao', models.CharField(choices=[('URGENTE', 'Urgente'), ('ALTA', 'Alta'), ('MEDIA', 'Média'), ('BAIXA', 'Baixa')], default='MEDIA', max_length=10)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Natureza/Categoria de Despesa',
                'verbose_name_plural': 'Naturezas/Categorias de Despesa',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='OrgaoSecretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('codigo_orcamentario', models.CharField(max_length=30, unique=True)),
                ('unidade_gestora', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Órgão/Secretaria',
                'verbose_name_plural': 'Órgãos/Secretarias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('objeto', models.CharField(max_length=255)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='cadastros.fornecedor')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='cadastros.orgaosecretaria')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-vigencia_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(help_text='Ex.: Conta Movimento — Secretaria de Saúde', max_length=150)),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.CharField(max_length=30)),
                ('grupo_despesa', models.CharField(choices=[('PESSOAL', 'Pessoal e Encargos Sociais'), ('CUSTEIO', 'Outras Despesas Correntes (Custeio)'), ('INVESTIMENTO', 'Investimentos'), ('DIVIDA', 'Amortização da Dívida'), ('OUTRAS', 'Outras Despesas de Capital')], max_length=20)),
                ('saldo_minimo_alerta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ativa', models.BooleanField(default=True)),
                ('fonte_recursos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_bancarias', to='cadastros.fonterecursos')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AlcadaAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('natureza', models.ForeignKey(blank=True, help_text='Deixe em branco para aplicar como limite geral do perfil.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.naturezadespesa')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcadas', to='accounts.perfilusuario')),
            ],
            options={
                'verbose_name': 'Alçada de Autorização',
                'verbose_name_plural': 'Alçadas de Autorização',
                'unique_together': {('perfil', 'natureza')},
            },
        ),
    ]
